/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/agentwp/v1/intent': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Submit an intent */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['IntentRequest'];
        };
      };
      responses: {
        /** @description Intent handled */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['IntentResponse'];
          };
        };
        /** @description Invalid payload */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Rate limit exceeded */
        429: {
          headers: {
            'Retry-After'?: number;
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/agentwp/v1/settings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get settings */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Settings payload */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['SettingsResponse'];
          };
        };
      };
    };
    put?: never;
    /** Update settings */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['SettingsUpdateRequest'];
        };
      };
      responses: {
        /** @description Updated settings */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['SettingsResponse'];
          };
        };
        /** @description Invalid payload */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/agentwp/v1/settings/api-key': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Store OpenAI API key */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['ApiKeyRequest'];
        };
      };
      responses: {
        /** @description API key stored */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApiKeyResponse'];
          };
        };
        /** @description Invalid API key */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/agentwp/v1/usage': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get usage stats */
    get: {
      parameters: {
        query?: {
          period?: 'day' | 'week' | 'month';
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Usage stats */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['UsageResponse'];
          };
        };
        /** @description Invalid period */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/agentwp/v1/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health check */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Health status */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['HealthResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/agentwp/v1/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Search indexed resources */
    get: {
      parameters: {
        query: {
          q: string;
          types?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Search results */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['SearchResponse'];
          };
        };
        /** @description Invalid query */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/agentwp/v1/history': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get command history */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description History payload */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['HistoryResponse'];
          };
        };
      };
    };
    put?: never;
    /** Update command history */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['HistoryUpdateRequest'];
        };
      };
      responses: {
        /** @description History updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['HistoryUpdateResponse'];
          };
        };
        /** @description Invalid payload */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/agentwp/v1/theme': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get theme preference */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Theme payload */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ThemeResponse'];
          };
        };
      };
    };
    put?: never;
    /** Update theme preference */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ThemeUpdateRequest'];
        };
      };
      responses: {
        /** @description Theme updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ThemeUpdateResponse'];
          };
        };
        /** @description Invalid theme */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ErrorObject: {
      code: string;
      message: string;
      type?: string;
      meta?: {
        [key: string]: unknown;
      };
    };
    ErrorResponse: {
      /** @enum {boolean} */
      success: false;
      data: Record<string, never>;
      error: components['schemas']['ErrorObject'];
    };
    IntentRequest:
      | {
          prompt?: string;
          input?: string;
          context?: {
            [key: string]: unknown;
          };
          metadata?: {
            [key: string]: unknown;
          };
        }
      | unknown
      | unknown;
    IntentResponseData: {
      intent_id?: string;
      status?: string;
      intent?: string;
      message?: string;
      draft?: {
        [key: string]: unknown;
      };
      cards?: {
        [key: string]: unknown;
      }[];
      function_suggestions?: string[];
    } & {
      [key: string]: unknown;
    };
    IntentResponse: {
      success: boolean;
      data: components['schemas']['IntentResponseData'];
    };
    Settings: {
      /** @enum {string} */
      model?: 'gpt-4o' | 'gpt-4o-mini';
      budget_limit?: number;
      draft_ttl_minutes?: number;
      hotkey?: string;
      /** @enum {string} */
      theme?: 'light' | 'dark';
      demo_mode?: boolean;
    };
    SettingsResponseData: {
      settings?: components['schemas']['Settings'];
      api_key_last4?: string;
      has_api_key?: boolean;
      api_key_status?: string;
      updated?: boolean;
    };
    SettingsResponse: {
      success: boolean;
      data: components['schemas']['SettingsResponseData'];
    };
    SettingsUpdateRequest: {
      /** @enum {string} */
      model?: 'gpt-4o' | 'gpt-4o-mini';
      budget_limit?: number;
      draft_ttl_minutes?: number;
      hotkey?: string;
      /** @enum {string} */
      theme?: 'light' | 'dark';
      dark_mode?: boolean;
      demo_mode?: boolean;
    };
    ApiKeyRequest: {
      api_key?: string;
    };
    ApiKeyResponseData: {
      stored?: boolean;
      last4?: string;
    };
    ApiKeyResponse: {
      success: boolean;
      data: components['schemas']['ApiKeyResponseData'];
    };
    UsageResponseData: {
      period?: string;
      total_tokens?: number;
      total_cost_usd?: number;
      breakdown_by_intent?: {
        [key: string]: unknown;
      };
      daily_trend?: {
        [key: string]: unknown;
      }[];
      period_start?: string;
      period_end?: string;
    };
    UsageResponse: {
      success: boolean;
      data: components['schemas']['UsageResponseData'];
    };
    HealthResponseData: {
      status?: string;
      time?: string;
      /** Format: int64 */
      timestamp?: number;
      version?: string;
    };
    HealthResponse: {
      success: boolean;
      data: components['schemas']['HealthResponseData'];
    };
    SearchResult: {
      id?: number;
      type?: string;
      primary?: string;
      secondary?: string;
      query?: string;
    };
    SearchResults: {
      [key: string]: components['schemas']['SearchResult'][];
    };
    SearchResponseData: {
      query?: string;
      results?: components['schemas']['SearchResults'];
    };
    SearchResponse: {
      success: boolean;
      data: components['schemas']['SearchResponseData'];
    };
    HistoryEntry: {
      raw_input?: string;
      parsed_intent?: string;
      timestamp?: string;
      was_successful?: boolean;
    };
    HistoryResponseData: {
      history?: components['schemas']['HistoryEntry'][];
      favorites?: components['schemas']['HistoryEntry'][];
      updated?: boolean;
    };
    HistoryResponse: {
      success: boolean;
      data: components['schemas']['HistoryResponseData'];
    };
    HistoryUpdateRequest: {
      history?: components['schemas']['HistoryEntry'][];
      favorites?: components['schemas']['HistoryEntry'][];
    };
    HistoryUpdateResponse: {
      success: boolean;
      data: components['schemas']['HistoryResponseData'];
    };
    ThemeUpdateRequest: {
      /** @enum {string} */
      theme: 'light' | 'dark';
    };
    ThemeResponseData: {
      theme?: string;
      updated?: boolean;
    };
    ThemeResponse: {
      success: boolean;
      data: components['schemas']['ThemeResponseData'];
    };
    ThemeUpdateResponse: {
      success: boolean;
      data: components['schemas']['ThemeResponseData'];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
